{% set version = "0.4.2" %}

package:
  name: sphinx-csv-filter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx-csv-filter/sphinx_csv_filter-{{ version }}.tar.gz
  sha256: e6d1614ca30d85403a5ce668f6348a9aeecab8bf7238a3d13723d3c56e9daa34

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - docutils <0.19
    - python >={{ python_min }}
    - sphinx

test:
  imports:
    - crate.sphinx.csv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/crate/sphinx_csv_filter
  summary: Sphinx CSV filter extension for Crate Documentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
