{% set version = "0.4.0" %}

package:
  name: sphinx-csv-filter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-csv-filter/sphinx-csv-filter-{{ version }}.tar.gz
  sha256: 4e8b6e85d3141e93fc9df51b5530e4565fd50bbc3fcec12306b83cb98b1f942d
  
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - docutils <0.19
    - python >=3.3
    - sphinx

test:
  imports:
    - crate
    - crate.sphinx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/crate/sphinx_csv_filter
  summary: Sphinx CSV filter extension for Crate Documentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
